export const PVP_ERROR_CODES = {
  TOKEN_EXPIRED: "PVP_TOKEN_EXPIRED",
  INVALID_TOKEN: "PVP_INVALID_TOKEN",
  BAD_SECRET: "PVP_BAD_SECRET",
  AUTH_FAILED: "PVP_AUTH_FAILED",
  INPUT_NONCE_MISSING: "PVP_INPUT_NONCE_MISSING",
  INPUT_NONCE_INVALID: "PVP_INPUT_NONCE_INVALID",
  QUEUE_SOCKET_NOT_READY: "PVP_QUEUE_SOCKET_NOT_READY",
  QUEUE_CONNECTION_CLOSED: "PVP_QUEUE_CONNECTION_CLOSED",
  MATCH_SESSION_SUPERSEDED: "PVP_MATCH_SESSION_SUPERSEDED",
  QUEUE_GATEWAY_DRAINING: "PVP_QUEUE_GATEWAY_DRAINING",
  QUEUE_USER_UNAVAILABLE: "PVP_QUEUE_USER_UNAVAILABLE",
  QUEUE_ALREADY_SEARCHING: "PVP_QUEUE_ALREADY_SEARCHING",
  QUEUE_MATCH_CREATION_FAILED: "PVP_QUEUE_MATCH_CREATION_FAILED",
  QUEUE_AI_FALLBACK_FAILED: "PVP_QUEUE_AI_FALLBACK_FAILED",
} as const;

export type PvpErrorCode = (typeof PVP_ERROR_CODES)[keyof typeof PVP_ERROR_CODES];

export type PvpErrorPayload = {
  message: string;
  code?: PvpErrorCode;
  retryable?: boolean;
  details?: {
    requestId?: string;
    phase?: string;
  };
};

export function isPvpErrorCode(value: unknown): value is PvpErrorCode {
  return typeof value === "string" && Object.values(PVP_ERROR_CODES).includes(value as PvpErrorCode);
}
