import type { Metadata } from "next";
import { Inter, Sora, Source_Code_Pro, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Background from "@/components/ui/Background";
import { LevelProvider } from "@/features/level/context/LevelProvider";
import { AlertProvider } from "@/contexts/alert-context";
import { AlertState } from "@/components/ui/alert-state";
import { HandleAuthSuccess } from "@/components/handle-auth-success";
import { DevPanelsWrapper } from "@/components/dev/DevPanelsWrapper";
import { auth } from "@/features/auth/lib/auth";
import { SettingsProvider } from "@/features/settings/context";
import { MotionSettingsProvider } from "@/components/providers/MotionSettingsProvider";
import { AudioProvider } from "@/features/audio/context";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
  adjustFontFallback: false, // Disable to prevent Turbopack issues
});

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  preload: true,
  weight: ["300", "400", "600"],
  variable: "--font-sora",
});

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  display: "swap",
  preload: true,
  weight: ["400", "600", "700"],
  variable: "--font-code",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  preload: true,
  weight: ["300"],
  variable: "--font-grotesk",
});

export const metadata: Metadata = {
  title: "Type Ocean",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const initialUserId = session?.user?.id ?? null;

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${sora.variable} ${sourceCodePro.variable} ${spaceGrotesk.variable} antialiased bg-n-11 font-sans text-n-1 text-base`}
        suppressHydrationWarning={true}
      >
        <Background className="fixed inset-0 pointer-events-none z-0" />

        <div className="relative z-10 min-h-screen flex flex-col">
          <SettingsProvider>
            <MotionSettingsProvider>
              <AudioProvider>
                <LevelProvider initialUserId={initialUserId}>
                  <AlertProvider>
                    <AlertState />
                    <HandleAuthSuccess />
                    {process.env.NODE_ENV !== "production" && <DevPanelsWrapper />}
                    <main className="flex-grow">{children}</main>
                    <Footer />
                  </AlertProvider>
                </LevelProvider>
              </AudioProvider>
            </MotionSettingsProvider>
          </SettingsProvider>
        </div>
      </body>
    </html>
  );
}
