import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer";
import Background from "@/components/ui/Background";
import { LevelProvider } from "@/contexts/LevelContext";
import { AlertProvider } from "@/contexts/alert-context";
import { AlertState } from "@/components/ui/alert-state";
import { AnimatePresence } from "framer-motion";

const inter = Inter({
  subsets: ["latin"], // You can choose another subset if needed
  preload: true,
});

export const metadata: Metadata = {
  title: "Type Ocean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${inter.className} antialiased bg-n-11 font-sans text-n-1 text-base min-h-full relative`}
      >
        <Background className="fixed inset-0 pointer-events-none -z-10" />

        <LevelProvider>
          <AlertProvider>
            <Header />
            <main className="relative z-10 min-h-screen overflow-hidden pointer-events-auto">
              <AnimatePresence mode="wait">
                <AlertState />
              </AnimatePresence>
              {children}
            </main>
          </AlertProvider>
        </LevelProvider>

        <Footer />
      </body>
    </html>
  );
}
